apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 108302758118.dkr.ecr.eu-west-2.amazonaws.com/your-app-name:latest
        ports:
        - containerPort: 80
